version: "3.8"

services:
  discovery-server:
    build: ./discovery-server
    network_mode: host
    restart: always
    container_name: p2p-discovery-server

  peer:
    build: ./peer-client
    network_mode: host
    stdin_open: true # Mở luồng nhập liệu cho Username/Passphrase
    tty: true # Mở terminal ảo
    container_name: p2p-peer-client
